package weather

var WeatherDescriptions = map[int]string{
	0:  "Ясно",
	1:  "Преимущественно ясно",
	2:  "Переменная облачность",
	3:  "Пасмурно",
	45: "Туман",
	48: "Иней",
	51: "Легкая морось",
	53: "Морось",
	55: "Сильная морось",
	56: "Ледяная морось",
	57: "Сильная ледяная морось",
	61: "Слабый дождь",
	63: "Умеренный дождь",
	65: "Сильный дождь",
	66: "Слабый ледяной дождь",
	67: "Сильный ледяной дождь",
	71: "Слабый снегопад",
	73: "Умеренный снегопад",
	75: "Сильный снегопад",
	77: "Мелкий зернистый снег",
	80: "Слабый ливень",
	81: "Умеренный ливень",
	82: "Сильный ливень",
	85: "Небольшой снегопад",
	86: "Сильный снегопад",
	95: "Гроза",
	96: "Гроза с мелким градом",
	99: "Гроза с крупным градом",
}

var ImageSources = map[int]string{
	0:  "/static/icons/clear-day.svg",
	1:  "/static/icons/mostly-clear-day.svg",
	2:  "/static/icons/partly-cloudy-day.svg",
	3:  "/static/icons/overcast.svg",
	45: "/static/icons/fog.svg",
	48: "/static/icons/haze.svg",
	51: "/static/icons/drizzle.svg",
	53: "/static/icons/drizzle.svg",
	55: "/static/icons/extreme-drizzle.svg",
	56: "/static/icons/sleet.svg",
	57: "/static/icons/extreme-sleet.svg",
	61: "/static/icons/rain.svg",
	63: "/static/icons/overcast-rain.svg",
	65: "/static/icons/extreme-rain.svg",
	66: "/static/icons/sleet.svg",
	67: "/static/icons/extreme-sleet.svg",
	71: "/static/icons/snow.svg",
	73: "/static/icons/overcast-snow.svg",
	75: "/static/icons/extreme-snow.svg",
	77: "/static/icons/snow.svg",
	80: "/static/icons/rain.svg",
	81: "/static/icons/overcast-rain.svg",
	82: "/static/icons/extreme-rain.svg",
	85: "/static/icons/snow.svg",
	86: "/static/icons/extreme-snow.svg",
	95: "/static/icons/thunderstorms-drizzle.svg",
	96: "/static/icons/thunderstorms-hail.svg",
	99: "/static/icons/thunderstorms-extreme-hail.svg",
}

var NightImageSources = map[int]string{
	0: "/static/icons/clear-night.svg",
	1: "/static/icons/mostly-clear-night.svg",
	2: "/static/icons/partly-cloudy-night.svg",
}
